# Generated by Django 4.2.7 on 2024-03-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='postType',
            field=models.CharField(blank=True, choices=[('observations', 'observations'), ('portraits', 'portraits'), ('landscapes', 'landscapes'), ('bmx', 'bmx'), ('family', 'family')], default=None, max_length=75, null=True),
        ),
    ]
